* QDA by Projection project -- Numerical Analysis
This is the numerical analysis part of the *QDA by Projection*
project. There are two literate programming scripts:
- [[file:simulation.org]]
- [[file:real_data.org]]
In order to run those, you need to install the following *R* packages:
- [[https://github.com/ywwry66/QDA-by-Projection-R-Package][QDAP]] (our *QDA by Projection* method)
- [[https://cran.r-project.org/src/contrib/Archive/rda/][RDA]]
- [[https://ani.stat.fsu.edu/~mai/research.html][DSDA]]
- [[https://cran.r-project.org/web/packages/DAP/index.html][DAP]]
You would also need [[https://www.gnu.org/software/emacs/][GNU Emacs]] to run the code blocks in the org
files. Just use ~C-c C-c~ within each ~#+begin_src~ blocks and
~#+call~ block calls (these are called library of babel calls
technically).

Run all the code blocks (except the ones in Section [[file:simulation.org::*Various Code Blocks][Various Code
Blocks]]) in sequential order, and you will get two .RData files and a
bunch of images, which summarize the result of our numerical
analysis, under ~./out~. This will also insert table summaries in the
original org files. Be informed that calls to ~model evaluation~
blocks can take a long time. Just wait for it to finish.

Also note that the parallel computing code may not be compatible with
Windows machines, because it uses doSNOW instead of doMC, which
requires the manual passing of objects and variables. It should run
with Linux, macOS and other Unix-like operating systems.
